"""OpenAPI metadata for the products endpoints.

Kept out of `views.py` so the views stay limited to orchestration. Everything
here is evaluated at import time: decorating a view costs nothing per request.
"""

from drf_spectacular.utils import OpenApiExample, OpenApiResponse, extend_schema
from rest_framework import serializers

from products.api.serializers import (
    ProductInputSerializer,
    ProductOutputSerializer,
)

PRODUCTS_TAG = "Products"


class ErrorDetailSerializer(serializers.Serializer):
    status = serializers.IntegerField()
    type = serializers.CharField(help_text="Exception class name, e.g. InvalidPrice.")
    detail = serializers.CharField()


class ErrorResponseSerializer(serializers.Serializer):
    """The envelope every error response uses. See config/exception_handler.py."""

    error = ErrorDetailSerializer()


_INVALID_PRICE_EXAMPLE = OpenApiExample(
    "Negative price",
    value={
        "error": {
            "status": 400,
            "type": "InvalidPrice",
            "detail": "Price cannot be negative.",
        }
    },
    response_only=True,
)

_NOT_FOUND_EXAMPLE = OpenApiExample(
    "Unknown product",
    value={
        "error": {
            "status": 404,
            "type": "ProductNotFound",
            "detail": "Product 3f1c9d2e-8b7a-4c5d-9e6f-0a1b2c3d4e5f not found.",
        }
    },
    response_only=True,
)

_BAD_REQUEST = OpenApiResponse(
    response=ErrorResponseSerializer,
    description="Malformed payload, or a business rule was violated.",
    examples=[_INVALID_PRICE_EXAMPLE],
)

_NOT_FOUND = OpenApiResponse(
    response=ErrorResponseSerializer,
    description="No product exists with that id.",
    examples=[_NOT_FOUND_EXAMPLE],
)


list_products_schema = extend_schema(
    tags=[PRODUCTS_TAG],
    summary="List products",
    description="Returns every product. No pagination or filtering yet.",
    responses={200: ProductOutputSerializer(many=True)},
)

create_product_schema = extend_schema(
    tags=[PRODUCTS_TAG],
    summary="Create a product",
    description=(
        "The id is generated by the domain, not by the client or the database, "
        "so it is not part of the request body."
    ),
    request=ProductInputSerializer,
    responses={201: ProductOutputSerializer, 400: _BAD_REQUEST},
)

get_product_schema = extend_schema(
    tags=[PRODUCTS_TAG],
    summary="Get a product by id",
    responses={200: ProductOutputSerializer, 404: _NOT_FOUND},
)

update_product_schema = extend_schema(
    tags=[PRODUCTS_TAG],
    summary="Update a product",
    description="Full replacement: every writable field must be sent.",
    request=ProductInputSerializer,
    responses={200: ProductOutputSerializer, 400: _BAD_REQUEST, 404: _NOT_FOUND},
)

delete_product_schema = extend_schema(
    tags=[PRODUCTS_TAG],
    summary="Delete a product",
    responses={204: OpenApiResponse(description="Deleted."), 404: _NOT_FOUND},
)
