"""Write operations. Same rule as the queries: take the use case, map the result.

Business rules are not re-checked here. `ProductInput` declares shape only; a
negative price is rejected by the entity, exactly as it is over REST.
"""

from uuid import UUID

import strawberry
from strawberry.types import Info

from products.api.graphql.context import GraphQLContext
from products.api.graphql.types import ProductInput, ProductType


@strawberry.type
class Mutation:
    @strawberry.mutation(
        description="Create a product. The id is generated by the domain."
    )
    def create_product(
        self, info: Info[GraphQLContext, None], input: ProductInput
    ) -> ProductType:
        product = info.context.use_cases.create.execute(
            name=input.name,
            description=input.description,
            price=input.price,
        )
        return ProductType.from_entity(product)

    @strawberry.mutation(description="Replace every writable field of a product.")
    def update_product(
        self, info: Info[GraphQLContext, None], id: UUID, input: ProductInput
    ) -> ProductType:
        product = info.context.use_cases.update.execute(
            id,
            name=input.name,
            description=input.description,
            price=input.price,
        )
        return ProductType.from_entity(product)

    @strawberry.mutation(
        description="Delete a product. Returns the id that was removed."
    )
    def delete_product(self, info: Info[GraphQLContext, None], id: UUID) -> UUID:
        info.context.use_cases.delete.execute(id)
        return id
