# Generated by Django 6.0.4 on 2026-08-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
